### PR TITLE
UI enhancement for expandable FAB

### LINKED ISSUE #59: Improve the User Interface for Floating Add Button
**Current Problem**

Whenever the user clicks on the Add button (Floating Button) on home screen which is having documents listed. A jam-packed and frustrating interface appears where the text/description of floating items (Open Camera, Open Files) overlaps the background text (can be seen below). Which doesn’t look like a _good_ _interface._
<p align="center">

</p>

**Solution**

we can reduce the background visibility on floating button click. This will improve the visibility and hence the more clear UI.
Just for an example I am attaching the screenshot for the same thing implemented in skype application - which is making the background blur/less visible :
<p align="center">

</p>

So, I want to make the background blur which will make it look a lot beautiful and more focused on buttons, and hence making more handy and clearer UI to the user.

@mishraaditya595 What are your thoughts regarding this ?

If it is okay can you please assign me the issue so that I can move forward solving this issue ?

### PR DESCRIPTION
**Pull request by deepsjuneja**
## Related Issuse or bug
  - Info about Issue or bug
  - Issue: When the floating action button is expanded, it overlaps the background view, thereby disrupting the user's experience.

Fixes: #59[issue number that will be closed through this PR]

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

I have added code to decrease the opacity of background view (including toolbar and bottom navigation menu) when the floating action button is expanded, thereby improving the user's experience. Changes have been made to both HomeFragment and OCRFragment (both activities contain expandable floating action buttons).

Fill in the form: https://forms.gle/uTfMxj8282nzwPck8

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

I've tested my code by running it on my VIVO device which works on Android 9.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
A clear and concise description of it.
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
 
 
111536257-07277980-8790-11eb-91b2-975c18a95d80 | 
Screenshot_20210512_190613 | 
Screenshot_20210512_190618

### CODE REVIEW

**Comment by mishraaditya595** [comment]
Hey @deepsjuneja, good job on it. Have you tried looking for implementing scoped storage?

**Comment by deepsjuneja** [comment]
> Hey @deepsjuneja, good job on it. Have you tried looking for implementing scoped storage?

I'm working on it.
Kindly merge this pull request and review the level of linked issue as well.

**Comment by deepsjuneja** [comment]
Hey @mishraaditya595! May I know when this pull request will be merged, as it has already been 5 days since I had generated the pull request?

**Comment by deepsjuneja** [comment]
@mishraaditya595 Kindly update the label on PR #72. It says Level 2 instead of **Level2**, which is why I didn't get any score for it.

**Comment by mishraaditya595** [comment]
Check now

**Pull request merged**
